navigation:
  navbars:
    mainnav:
      brand: BrandText
      brandIcon: fa fa-check
      color: dark
      fixed: sticky
      searchenabled: true
      searchroute: homepage
      items:
        homepage:
          lib: homepage
          icon: fa fa-home
          route: homepage

  usermenu:
    activate: true
    connexionroute: homepage
    autolib: false
    childs:
      admin:
        lib: Administration
        icon: fa fa-cogs
        route: admin
      logout:
        lib: Sign-out
        icon: fa fa-sign-out-alt
        route: homepage