#index:
#    path: /
#    controller: App\Controller\DefaultController::index
ssi_bundle:
    resource: '@SsiBundle/config/routes.yaml'
    prefix: /ssi
dashboard_bundle:
    resource: '@DashboardBundle/config/routes.yaml'
    prefix: /dashboard
cron_bundle:
    resource: '@CronBundle/config/routes.yaml'
    prefix: /cron
qwant_bundle:
    resource: '@QwantBundle/config/routes.yaml'
    prefix: /qwant
celebrity_bundle:
    resource: '@CelebrityBundle/config/routes.yaml'
    prefix: /celebrity